# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2831b9cc5edd972c6ccf2c7743ce3676bca5a1b864e156619e47af7d19930100f0c59970faa4ac4d2ca71f20905d5c4111580d4e41066881ae66bf8ff4f5d402

test:
  secret_key_base: f5b90a07a1359fb79af245f77acae6ea78c0fffe8dba849ef44b29b5c2a1b6ff827532e2520ef771671c8bd5d0e5105ce6f934a6dd643647387589892f4319d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
